branch-defaults:
  master:
    environment: Blockswebserver2-env
environment-defaults:
  Blockswebserver2-env:
    branch: null
    repository: null
global:
  application_name: BlocksWebServer2
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: fusion-us-east-1
  repository: null
  sc: git
  workspace_type: Application
